Import and register chartjs 3 components
apertureless/vue-chartjs pull request #658
Opened 2020-11-06 19:28 UTC by zbateson

Imports all chartjs 3 components and registers them.

Unfortunately this would mean that the v3 version would not be compatible with chartjs 2, so not sure if you want to merge this like this, or if possible add some conditional so vue-chartjs works with both 2 and 3, or if that matters to this project (maybe only supporting 3 once it's out is all that's needed for a new version of vue-chartjs?)

All the same, thanks for putting this library together :)

2020-11-16 09:06 UTC, LeeLenaleee requested changes
Change import, register and new chart to this, think its more readable since its a lot less code and you now dont have the issue that you might have forgotten to import a specific thing

import * as ChartJs from 'chart.js';

ChartJs.Chart.register.apply(null, Object.values(ChartJs).filter((chartClass) => (chartClass.id)));

this.$data._chart = new ChartJs.Chart(

2020-11-16 17:26 UTC, zbateson commented
*way* better.

You mean that should be done in BaseChart.js or are you recommending users do that themselves?  Asking because BaseChart.js doesn't create the chart (the third line).  It had this:

```
import Chart from 'chart.js'
```
which now fails.  If it goes to the users to do the import, then the import line in BaseChart.js would need to be changed to whatever minimum is needed for vue-chartjs.

2020-11-16 17:42 UTC, zbateson commented
Aah, the 3rd line was further down -- gotcha... thanks @LeeLenaleee

2021-04-06 07:32 UTC, WikiRik commented
Chart.js 3 is out. Would this PR make it compatible? Then I suggest making this a breaking change and release it

2022-01-18 15:54 UTC, closed without merging