Add storybook
apertureless/vue-chartjs pull request #746
Opened 2022-01-13 19:46 UTC by thabarbados

### Fix or Enhancement?
Add storybook and stories for sandbox components

- [x] All tests passed

### Environment
- OS: BigSur MacOs
- NPM Version: 6.14.15

2022-01-17 07:03 UTC, dangreen requested changes
What about `.storybook/theme.js`?

2022-01-17 07:03 UTC, dangreen commented on package.json
> +    "storybook:build": "build-storybook"
We don't need to build this.

2022-01-17 07:03 UTC, dangreen commented on package.json
> +    "storybook:start": "start-storybook -p 6006",
```suggestion
    "start:storybook": "start-storybook -p 6006",
```

2022-01-17 07:03 UTC, dangreen commented on .storybook/main.js
> +  addons: ['@storybook/addon-links', '@storybook/addon-essentials'],
> `'@storybook/addon-links', '@storybook/addon-essentials'`

Is it used in stories?

2022-01-17 14:57 UTC, thabarbados commented on .storybook/.babelrc
> +  "extends": "./../.babelrc"
removed

2022-01-17 14:57 UTC, thabarbados commented on package.json
> +    "storybook:start": "start-storybook -p 6006",
fix

2022-01-17 14:58 UTC, thabarbados commented on .storybook/main.js
> +  addons: ['@storybook/addon-links', '@storybook/addon-essentials'],
`addon-links` not used. removed

2022-01-18 13:54 UTC, dangreen approved these changes

2022-01-18 13:55 UTC, merged