Add cube branding
apertureless/vue-chartjs pull request #776
Opened 2022-03-24 19:22 UTC by thabarbados

### Fix or Enhancement?
add cube branding and change readme header style

- [x] All tests passed

### Environment
- OS: BigSur MacOs
- NPM Version: 8.5.1

2022-03-24 20:19 UTC, dangreen requested changes

2022-03-24 20:19 UTC, dangreen commented on README.md
> +[![Build Status](https://travis-ci.org/apertureless/vue-chartjs.svg?branch=master)](https://github.com/apertureless/vue-chartjs/actions)
```suggestion
[![Build Status](https://img.shields.io/github/workflow/status/apertureless/vue-chartjs/CI.svg)](https://github.com/apertureless/vue-chartjs/actions)
```

2022-03-24 20:23 UTC, dangreen commented on README.md
> +## Docs
let's move it after "install" section?

2022-03-25 07:54 UTC, thabarbados commented on README.md
> +[![Build Status](https://travis-ci.org/apertureless/vue-chartjs.svg?branch=master)](https://github.com/apertureless/vue-chartjs/actions)
changed

2022-03-25 07:54 UTC, thabarbados commented on README.md
> +## Docs
moved

2022-03-25 09:29 UTC, dangreen approved these changes

2022-03-25 09:29 UTC, merged