Update docs
apertureless/vue-chartjs pull request #785
Opened 2022-03-29 09:41 UTC by thabarbados

### Fix or Enhancement?
Replacing vuepress with vitepress, update sandboxes and docs

- [x] All tests passed

### Environment
- OS: BigSur MacOs
- NPM Version: 8.5.1

2022-03-29 09:42 UTC, thabarbados commented
Hey, @apertureless, could you update the docs site after merging this MR?

2022-03-30 06:49 UTC, apertureless commented
@thabarbados The docs are hosted on github pages here.
You can just push it to the `gh-pages` branch and it will release it.

https://github.com/apertureless/vue-chartjs/blob/main/deploy-docs.sh

2022-03-31 16:31 UTC, dangreen requested changes

2022-03-31 16:31 UTC, dangreen commented on website/package.json
> +    "docs:build": "vitepress build docs"
```suggestion
    "dev": "vitepress dev src",
    "build": "vitepress build src"
```

lets mv docs -> src

2022-03-31 16:31 UTC, dangreen commented on website/docs/guide/index.md
> +### NPM
useless title

2022-03-31 16:31 UTC, dangreen commented on website/docs/guide/index.md
> +:::tip Need an API to fetch data?
lets move it under introduction

2022-04-01 07:30 UTC, thabarbados commented on website/docs/guide/index.md
> +### NPM
removed

2022-04-01 07:30 UTC, thabarbados commented on website/docs/guide/index.md
> +:::tip Need an API to fetch data?
moved

2022-04-01 07:52 UTC, dangreen approved these changes

2022-04-01 08:31 UTC, merged